<?php
/**
 * @file
 * Bundle and activate the Tabled plugin.
 */

/**
 * Implements hook_menu().
 */
function tabled_menu() {
  $items = array();

  $items['admin/config/user-interface/tabled'] = array(
    'title' => 'Tabled',
    'description' => 'Configuration for Tabled module',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tabled_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_config_info().
 */
function tabled_config_info() {
  $config = array();

  $config['tabled.settings'] = array(
    'label' => t('Tabled settings'),
    'group' => t('Configuration'),
  );

  return $config;
}

/**
 * Implements hook_library_info().
 *
 */
function tabled_library_info() {
  $path = backdrop_get_path('module', 'tabled') . '/';
  $libraries['tabled'] = array(
    'title' => 'Tabled',
    'website' => 'https://github.com/Lullabot/tabled',
    'version' => 'dev',
    'js' => array(
      $path . 'library/dist/tabled.js' => array(),
    ),
    'css' => array(
      $path . 'library/dist/theme.css' => array(),
      $path . 'library/dist/styles.css' => array(),
    ),
  );
  return $libraries;
}

/**
 * Configuraton form.
 */
function tabled_admin_settings($form, &$form_state) {

  $config = config('tabled.settings');

  $form['excluded_selectors'] = array(
    '#type' => 'textarea',
    '#title' => t('Excluded selectors'),
    '#default_value' => $config->get('excluded_selectors'),
    '#rows' => 3,
    '#description' => t('By default, Tabled will not be applied to any table with the <code>untabled</code> CSS class. You can add additional jQuery selectors here to exclude additional tables. Use a new line for each selector.'),
  );

  $form['actions']['#type'] = 'actions';
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Configuration'),
  );

  return $form;
}

/**
 *
 */
function tabled_admin_settings_submit ($form, &$form_state) {
  $config = config('tabled.settings');
  $values = $form_state['values'];
  $config->set('excluded_selectors', trim(check_plain($values['excluded_selectors'])));
  $config->save();

  backdrop_set_message(t('Settings have been saved.'));
}


/**
 * Implements hook_preprocess_page().
 */
function tabled_preprocess_page(&$variables) {
  // Performance: Skip this entirely for AJAX requests.
  if (!backdrop_is_html()) {
    return;
  }
  $current_path = current_path();
  if (!path_is_admin($current_path)) {
    $config = config('tabled.settings');

    // Get tabled excluded selectors.
    $excluded_selectors = $config->get('excluded_selectors');
    $excluded_selectors_array = explode(PHP_EOL, $excluded_selectors);

    // Export the variables to Backdrop.settings.
    backdrop_add_js(array('tabled' => array(
      'excluded_selectors' => $excluded_selectors_array,
    )), 'setting');

    $module_path = backdrop_get_path('module', 'tabled') . '/';
    backdrop_add_library('tabled', 'tabled');
    backdrop_add_js($module_path . 'js/tabled_init.js', array('scope' => 'footer'));
  }
}
